development:
  adapter: postgresql
  encoding: unicode
  database: session_trail_development
  pool: 5
  host: localhost
  username: nibabboo
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: session_trail_test
  pool: 5
  username: nibabboo
  password: 12345

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>